### ISSUE TITLE
how to set https certs

### ISSUE THREAD

**Issue by itplanes** [jsiebens/ionscale#11]
Hello, I can start success when dns enable

log:

```
ionscale_1  | Error: invalid MagicDNS suffix [ion.demo.site], not part of zone [cloudflare zone id]
```
domain set ion.demo.site or demo.site

```
dns:
  magic_dns_suffix: "ion.demo.site"
  provider:
    name: "cloudflare"
    zone: "cloudflare zone id"
    subdomain: ""
    config: {}
```
how to set cloudflare api secret?

**Comment by jsiebens** [comment]
hi @itplanes 

When enabling a dns provider for the https cert, the magicdns suffix should be a subdomain of the domain (or zone) you own and manage with the provider.
The cloudflare api secret is a provider specific configuration and can be set in the config part.

 E.g. when you own `demo.site`:
 
```
dns:
  magic_dns_suffix: "ion.demo.site"
  provider:
    name: "cloudflare"
    zone: "demo.site"
    config:
      api_token: "<your cloudflare api token>"
```

The cloudflare api token can also be set by using the environment variable `IONSCALE_DNS_CLOUDFLARE_API_TOKEN`
