### ISSUE TITLE
Can't get cloudflare API token to work

### ISSUE THREAD

**Issue by teleclimber** [jsiebens/ionscale#80]
Hi, I set up cloudflare as a DNS provider but I am getting an error. 

In cloudflare, I created a "User API Tokens" for the zone. I pasted the token directly into the config (not using a env var). Here is the config:

```
[...]
dns:
  magic_dns_suffix: "ionscale.<redacted>"

  provider:
    name: "cloudflare"
    zone: "<redacted>"
    config:
      auth_token: "5...redacted...g"

[...]
```

If I do `$ tailscale serve` it indicates that it's serving over https, but if I try to access it, I get a cert error. In the ionscale logs I get this:

```
ionscale        handlers/dns.go:41        error processing request  {"error": "got error status: HTTP 400: [{Code:6003 Message:Invalid request headers ErrorChain:[{Code:6111 Message:Invalid format for Authorization header}]}]"}
```

I've read through the readme and issues in [libdns](https://github.com/libdns/cloudflare). This error is indicative of using the ["wrong token"](https://github.com/libdns/cloudflare/issues/12). But I tried it with two different tokens and I get the same error. I checked and double checked the token string. I also curl'd using the token as cf recommends and it worked.

I might be missing something of course but I thought I'd post an issue in case something maybe changed in ionscale?

Thanks.
